/*
 * Copyright (C) 2017 Tim Clemens
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.tclemens.calcium.engine.updates.event;

import android.support.annotation.NonNull;

/**
 * This class represents an event generated by the engine
 *
 * @author Tim Clemens
 */
public abstract class Event implements Comparable<Event> {

    /** The time the event occurred in milliseconds */
    private final long time;

    /**
     * @param time The time the event occurred in milliseconds
     */
    Event(long time) {

        this.time = time;
    }

    /**
     * Get the time the event occurred in milliseconds
     *
     * @return The time the event occurred in milliseconds
     */
    public final long getTime() {

        return time;
    }

    @Override
    public final int compareTo(@NonNull Event other) {

        return time == other.time ? 0 : (time < other.time ? -1 : 1);
    }
}
